-- liquibase formatted sql

-- changeset romantimosenko:1732302826075-1
CREATE TABLE user_entity
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

-- changeset romantimosenko:1732302826075-2
ALTER TABLE user_entity
    ADD CONSTRAINT uc_userentity_email UNIQUE (email);

-- changeset romantimosenko:1732302826075-3
ALTER TABLE user_entity
    ADD CONSTRAINT uc_userentity_username UNIQUE (username);

