-- liquibase formatted sql

-- changeset romantimosenko:1732964629237-1
CREATE TABLE blog_entity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      VARCHAR(150)                            NOT NULL,
    content    VARCHAR(10000)                          NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    creator_id BIGINT,
    CONSTRAINT pk_blog_entity PRIMARY KEY (id)
);

